### ISSUE TITLE
Example programs should be in subdirectory

### ISSUE THREAD

**Issue by thetoster** [edrosten/libblepp#11]
Just a small request. All examples or code which is not a part of library itself should be in separate directory. This will simplify life of others who would like to use lib. At current moment I've to add a lot of excludes per each file in my IDE to not compile things which I don't need.

**Comment by edrosten** [comment]
On 20 April 2017 at 16:25, Bartłomiej Żarnowski <notifications@github.com>
wrote:

> Just a small request. All examples or code which is not a part of library
> itself should be in separate directory. This will simplify life of others
> who would like to use lib. At current moment I've to add a lot of excludes
> per each file in my IDE to not compile things which I don't need.
>

Yeah good point. It wasn't going to be a library initially!

The library code should all be in src/. I really ought to move the rest to
examples/

-Ed

**Comment by edrosten** [comment]
Fixed
