### ISSUE TITLE
Lack of call to cb_disconnected on close()

### ISSUE THREAD

**Issue by thetoster** [edrosten/libblepp#13]
Library is not calling callback cb_disconnected after call to close().
This is unexpected, since I got callback cb_connected when connection establish, so after close I would expect to have cb_disconnected. I digged a little in your code and looks like you executing cb_disconnected in few places, sometimes after call to close() so adding this callback inside close is not an option. I believe there can be 2 close implementations:
1) current close() move to innerClose() and all current calls should use this.
2) create public close() which will call innerClose and cb_disconnected.

**Comment by edrosten** [comment]
Sounds like a good plan. Can you send a pull request?

sent from phone.

**Comment by thetoster** [comment]
Yep, but I'm not sure of your architecture that's why I didn't send any PR. There is several things which I would redesign/changed but I don't want to do major changes in your code. Instead I've wrapped what I need and limited interaction with your code. Not a good approach but I want to make my project stable at first.

**Comment by edrosten** [comment]
Oh sure. The architecture isn't set in stone and I'm certainly happy to
make changes. That one doesn't sound huge..

sent from phone.

**Comment by edrosten** [comment]
The callback is now called on close()
