### ISSUE TITLE
Notification with send_write_command/send_write_request

### ISSUE THREAD

**Issue by Stretchdude** [edrosten/libblepp#20]
Hello,
first thank you for this great lib!
I couldn't get notifications to work. After some debugging it looks like changing the "write" in method "set_notify_and_indicate" to a request rather than a command helped. 
Is this a bug in my BLE device or a problem with libblepp?
Regards Ben

**Comment by edrosten** [comment]
On 26 January 2018 at 11:14, Stretchdude <notifications@github.com> wrote:

> Hello,
> first thank you for this great lib!
> I couldn't get notifications to work. After some debugging it looks like
> changing the "write" in method "set_notify_and_indicate" to a request
> rather than a command helped.
> Is this a bug in my BLE device or a problem with libblepp?
>

Both? libblepp should offer both options. There might be a bug in your
device too in that it ought to respond to both, but I'm not sure enough of
the BLE spec to know if that's the case.

If you want to add a second method, please send me a PR!



-Ed

Regards Ben

**Comment by edrosten** [comment]
Hi

The patch didn't apply cleanly against HEAD. Can you try a git pull and re-send the new patch?

**Comment by Stretchdude** [comment]
I created a PR. Hope this works better.

**Comment by Stretchdude** [comment]
Okay. Tested now with your last changes. Works fine :-) Thank you again.
