### ISSUE TITLE
verison number?

### ISSUE THREAD

**Issue by nico202** [edrosten/libblepp#24]
Hi, how stable this library is? Is there a version number?
If there's, would you mind tagging it? I'm thinking of basing my new project on this library :)

**Comment by edrosten** [comment]
On 17 February 2018 at 10:17, Nicolò Balzarotti <notifications@github.com>
wrote:

> Hi, how stable this library is? Is there a version number?
> If there's, would you mind tagging it? I'm thinking of basing my new
> project on this library :)
>

Hi,

It's stable, as in I won't be breaking the API in the forseeable future,
though I will probably add features to it occasionally.

I've got it controlling a piece of kit an a factory you see, so I have a
strong incentive to keep it from breaking :)

There's no version number though, I did it by git hash. Maybe it's time to
be 1.0

-Ed

**Comment by edrosten** [comment]
It's been in use ages and seems fine. Tagging as 1.0
