### ISSUE TITLE
-lble++ flag missing

### ISSUE THREAD

**Issue by nico202** [edrosten/libblepp#25]
Hi, after compiling the library the pkgconfig/libblepp.pc set 
```
Libs: -lbluetooth
```
while it should have -lble++ too in order to link to this

**Comment by edrosten** [comment]
closed with [ 4997a41](https://github.com/edrosten/libblepp/commit/4997a4103848f16556b007dce354200a2a9e9b94)

**Comment by edrosten** [comment]
Thanks for the bug report!
