### ISSUE TITLE
Function not implemented - blestatemachine.cc

### ISSUE THREAD

**Issue by mswilk67** [edrosten/libblepp#26]
In blestatemachine.cc, there's a log_fd call that prints a log message "Function not implemented" at line 296. The message can be ignored but is falsely reporting a problem. The return value for ::connect() is 0 for success and thus the macro fails and prints the message.

**Comment by edrosten** [comment]
Sorry for the slow reply: log_fd shouldn't print anything if it's passed a 0. What happens next?

**Comment by mswilk67** [comment]
Seems to just continue on its merry way but appears as a false positive error/warning.

**Comment by edrosten** [comment]
I'm kind of stumped. I can't see why it's getting past that point. Could you run the library in the most verbose mode and paste the log?

**Comment by edrosten** [comment]
Ah OK, thanks for letting me know. I know what you mean about the RPi: that was the original deployment platform for this library. I also found that the chip did some very unusual but technically compliant things.
