### ISSUE TITLE
Is libblepp based on libbluetooth / GPL?

### ISSUE THREAD

**Issue by alexe100** [edrosten/libblepp#51]
Hi !
I am looking for a way to implement BLE scann using linux and I found libblep whch is excellent for my problem. 
As far as I know, libbluetooth (from ) is based on D-Bus APIs, right? You are saying that libblepp does not uses D-Bus. Does this means that libblepp is self contained (does not uses any other libraries success as libbluetooth.so or libbluetooth.h)?

My problem is: AFAIK libbluetooth.so and libbluetooth.h are GPL. libblepp is not?  So if I use libblepp for my listenning linux program should I release program under GPL? Can I release it as closed source?

Thanks a lot
Alex

**Comment by edrosten** [comment]
Most of the normal bluetooth stuff is dbus based. My library doesn't use dbus. I do use bits of libbluetooth, so both me and you are stuck with the GPL.

**Comment by alexe100** [comment]
Great! just to clarify
