### ISSUE TITLE
configure: error: bluez bluetooth missing

### ISSUE THREAD

**Issue by kcherneha** [edrosten/libblepp#57]
Hi, got this error in installation process.

Environment: Linux Ubuntu 18.04, x86_64.
bluez version (5.48-0ubuntu3.4)
bluetooth version (5.48-0ubuntu3.4).
Also, downloaded and installed ELL 0.9 version from this site:
https://mirrors.edge.kernel.org/pub/linux/libs/ell/

Full logs:
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking if compiler flag -Wall works... yes
checking if compiler flag -Wextra works... yes
checking if compiler flag -W works... yes
checking if compiler flag -O3 works... yes
checking if compiler flag -ggdb works... yes
checking whether g++ supports C++14 features by default... yes
checking for pkg-config... /usr/bin/pkg-config
checking for sed... sed
checking for pkg-config library dir... ${exec_prefix}/lib/pkgconfig
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking bluetooth/bluetooth.h usability... no
checking bluetooth/bluetooth.h presence... no
checking for bluetooth/bluetooth.h... no
checking for library containing hci_open_dev... no
configure: error: bluez bluetooth missing

Could you please help with installation? Thanks.

**Comment by edrosten** [comment]
Do you have the bluez-dev libraries installed?

**Comment by kcherneha** [comment]
@edrosten, thanks for replying.
I missed libbluetooth-dev (maybe aka bluez-dev), and after that configuration was succeeded. Thanks!
