### ISSUE TITLE
I/O error & Switching off HCI scanner

### ISSUE THREAD

**Issue by saeedamiri92** [edrosten/libblepp#64]
Hi, I trying to run "lescan_simple" from examples.
the environment is ubuntu 20.04 in VM.
I compiled and ran the program, but I got an error and execution aborted with following msg.
```
warn  1643202449.692793: Received I/O error while setting scan parameters.
warn  1643202449.692880: Switching off HCI scanner
error 1643202449.695767: Error disabling scan:: Input/output error
terminate called after throwing an instance of 'BLEPP::HCIScanner::IOError'
  what():  Error disabling scan:: Input/output error
Aborted

```
the problem related to `HCIScanner` of bellow command:
`BLEPP::HCIScanner scanner;`

Can anyone help me to fix the problem?
any idea

**Comment by edrosten** [comment]
Are you running as root?

**Comment by saeedamiri92** [comment]
> Are you running as root?

YES

**Comment by saeedamiri92** [comment]
I have completed the following steps:
1. clone
2. cmake
3. make install
4. compile by: `g++ lescan_simple.cc -o lescan_simple --std=c++11 -lble++ -lbluetooth`

**Comment by edrosten** [comment]
Hard to tell. Something else might also be connected to the control mode of
the bluetooth adapter (try disabling all bluetooth services), or possibly
the VM has insufficient permissions on the device: according to the HCI
protocol setting/disabling scanning has the same level of access as that
needed to snoop on all traffic.

**Comment by saeedamiri92** [comment]
Yes, that's right. I tested this library on an Ubuntu that installed directly on the system and found no errors.
